/**
 * List of operation IDs currently implemented by soundcloud-api-ts.
 * Used for OpenAPI coverage reporting.
 */
export const IMPLEMENTED_OPERATIONS: string[] = [
  // Auth
  "post_oauth2_token",
  "delete_oauth2_token",

  // Me
  "get_me",
  "get_me_activities",
  "get_me_activities_own",
  "get_me_activities_tracks",
  "get_me_likes_tracks",
  "get_me_likes_playlists",
  "get_me_followings",
  "get_me_followings_tracks",
  "post_me_followings_user_id",
  "delete_me_followings_user_id",
  "get_me_followers",
  "get_me_playlists",
  "get_me_tracks",
  "get_me_connections",

  // Users
  "get_users_user_id",
  "get_users_user_id_followers",
  "get_users_user_id_followings",
  "get_users_user_id_tracks",
  "get_users_user_id_playlists",
  "get_users_user_id_likes_tracks",
  "get_users_user_id_likes_playlists",
  "get_users_user_id_web_profiles",

  // Tracks
  "get_tracks_track_id",
  "put_tracks_track_id",
  "delete_tracks_track_id",
  "get_tracks_track_id_comments",
  "post_tracks_track_id_comments",
  "get_tracks_track_id_likes",
  "get_tracks_track_id_reposts",
  "get_tracks_track_id_related",
  "get_tracks_track_id_streams",
  "post_likes_tracks_track_id",
  "delete_likes_tracks_track_id",
  "post_reposts_tracks_track_id",
  "delete_reposts_tracks_track_id",

  // Playlists
  "get_playlists_playlist_id",
  "post_playlists",
  "put_playlists_playlist_id",
  "delete_playlists_playlist_id",
  "get_playlists_playlist_id_tracks",
  "get_playlists_playlist_id_reposts",
  "post_likes_playlists_playlist_id",
  "delete_likes_playlists_playlist_id",
  "post_reposts_playlists_playlist_id",
  "delete_reposts_playlists_playlist_id",

  // Search
  "get_tracks",
  "get_users",
  "get_playlists",

  // Resolve
  "get_resolve",
];

/**
 * Official spec paths implemented by this package (`METHOD path`).
 * Source of truth for coverage now that the public OpenAPI spec has no operationIds.
 */
export const IMPLEMENTED_ROUTES: string[] = [
  "POST /oauth/token",
  "POST /sign-out",
  "GET /me",
  "GET /me/activities",
  "GET /me/activities/all/own",
  "GET /me/activities/tracks",
  "GET /me/feed",
  "GET /me/feed/tracks",
  "GET /me/recently-played/tracks",
  "GET /me/reposts/tracks",
  "GET /me/reposts/playlists",
  "GET /me/likes/tracks",
  "GET /me/likes/playlists",
  "GET /me/followings",
  "GET /me/followings/tracks",
  "PUT /me/followings/{user_urn}",
  "DELETE /me/followings/{user_urn}",
  "GET /me/followers",
  "GET /me/playlists",
  "GET /me/tracks",
  "GET /me/connections",
  "GET /users/{user_urn}",
  "GET /users/{user_urn}/followers",
  "GET /users/{user_urn}/followings",
  "GET /users/{user_urn}/tracks",
  "GET /users/{user_urn}/playlists",
  "GET /users/{user_urn}/likes/tracks",
  "GET /users/{user_urn}/likes/playlists",
  "GET /users/{user_urn}/web-profiles",
  "GET /users/{user_urn}/related",
  "GET /users/{user_urn}/reposts/tracks",
  "GET /users/{user_urn}/reposts/playlists",
  "GET /tracks/{track_urn}",
  "POST /tracks",
  "PUT /tracks/{track_urn}",
  "DELETE /tracks/{track_urn}",
  "GET /tracks/{track_urn}/comments",
  "POST /tracks/{track_urn}/comments",
  "GET /tracks/{track_urn}/favoriters",
  "GET /tracks/{track_urn}/reposters",
  "GET /tracks/{track_urn}/related",
  "GET /tracks/{track_urn}/streams",
  "GET /tracks/{track_urn}/stream",
  "GET /tracks/{track_urn}/preview",
  "PUT /tracks/{track_urn}/storefront",
  "POST /likes/tracks/{track_urn}",
  "DELETE /likes/tracks/{track_urn}",
  "POST /reposts/tracks/{track_urn}",
  "DELETE /reposts/tracks/{track_urn}",
  "GET /playlists/{playlist_urn}",
  "POST /playlists",
  "PUT /playlists/{playlist_urn}",
  "DELETE /playlists/{playlist_urn}",
  "GET /playlists/{playlist_urn}/tracks",
  "GET /playlists/{playlist_urn}/reposters",
  "POST /likes/playlists/{playlist_urn}",
  "DELETE /likes/playlists/{playlist_urn}",
  "POST /reposts/playlists/{playlist_urn}",
  "DELETE /reposts/playlists/{playlist_urn}",
  "GET /tracks",
  "GET /users",
  "GET /playlists",
  "GET /resolve",
];
